---
- name: Create local user for makepkg
  user: name=makepkg shell=/bin/sh

- name: Copy aur script
  copy: src=files/bin/aur dest=/usr/local/bin/aur mode=755

- name: Install base-devel
  pacman: name=base-devel state=present

- name: Install yay
  aur: name=yay-bin skip_installed=yes use=makepkg
  become: yes
  become_user: makepkg
