---
# Workaround to avoid https://github.com/ansible/ansible/issues/37334
- command: pacman -Qi base
  changed_when: False
  register: base_package_present
- command: pacman -S --noconfirm base
  when: base_package_present.rc != 0

- name: Install base
  pacman: name=base state=present

- name: Install minimal base
  pacman:
    name:
      # These used to be part of the base group, but aren't part of the new
      # metapackage. After new `base` becomes stable, these should be moved to
      # relevant sections and justified there.
      - cryptsetup
      - device-mapper
      - dhcpcd
      - diffutils
      - less
      - linux-firmware
      - man-db
      - man-pages
      - netctl

- name: Install tools that don't require Ansible configuration (all)
  pacman:
    name:
      - ansible
      - vim
      - rsync
      - tmux
      - git
      - openssh
      - htop
      - mupdf
      - btrfs-progs
      - graphviz
      - aspell
      - aspell-en

- name: Install dmenu-git (here to avoid conflict from revdeps)
  aur: name=dmenu-git skip_installed=yes skip_pgp_check=yes
  become: yes
  become_user: makepkg

- name: Install tools that don't require Ansible configuration (Chris specific)
  when: not minimal
  pacman:
    name:
      - lsof
      - reflector
      - p7zip
      - maim
      - slop  # optdepends for `screenshot --select`
      - openconnect
      - msmtp
      - xclip
      - pass
      - irssi
      # For duply
      - python-boto
      - parallel
      - pdfpc
      - enca
      - android-tools
      - android-udev
      - hugin
      - gimp
      - rustup
      - imagemagick
      - ghostscript # for imagemagick
      - mpv
      - ncdu
      - openbox  # presentations
      - libreoffice-still
      - mktorrent
      - mpd
      - mpc
      - easytag
      - udftools
      - pacman-contrib
      - qemu
      - exfat-utils
      - ctags
      - bind-tools
      - python-virtualenvwrapper
      - powertop
      - redshift
      - asp
      - colordiff
      - clipmenu
      - zsh-syntax-highlighting
      - rtorrent
      - xdotool
      - shellcheck

- name: Install basic tools requiring aur (Chris specific)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes
  when: not minimal
  with_items:
    - cconv
    - duply
    - drive-bin
    - pngquant
    - sshrc
    - xinput-toggle
    - nota
    - mpdscribble
    - mpdmenu
    - btmenu
    - geteltorito
    - google-chrome
    - downgrade
    - sxiv-cdown-git
    - gimp-plugin-resynthesizer
    - acestream-engine-stable
    - spotify
    - nocache
    - whatmp3
    - psi-notify
  become: yes
  become_user: makepkg

- name: Install laptop tools
  aur: name={{ item }} skip_installed=yes
  with_items:
    - bats
  when: laptop|bool
  become: yes
  become_user: makepkg

- name: Install nsswitch.conf
  copy: src=files/nsswitch.conf dest=/etc/nsswitch.conf

- name: Install ImageMagick policy
  copy: src=files/policy.xml dest=/etc/ImageMagick-7/policy.xml

- name: Install vconsole config
  copy: src=files/vconsole.conf dest=/etc/vconsole.conf
