---
# Workaround to avoid https://github.com/ansible/ansible/issues/37334
- command: pacman -Qi base
  changed_when: False
  register: base_package_present
- command: pacman -S --noconfirm base
  when: base_package_present.rc != 0

- name: Install base
  pacman: name=base state=present

- name: Install minimal base
  pacman:
    name:
      # These used to be part of the base group, but aren't part of the new
      # metapackage. After new `base` becomes stable, these should be moved to
      # relevant sections and justified there.
      - cryptsetup
      - device-mapper
      - dhcpcd
      - diffutils
      - less
      - linux-firmware
      - man-db
      - man-pages
      - netctl

- name: Install tools that don't require Ansible configuration (all)
  pacman:
    name:
      - ansible
      - vim
      - rsync
      - tmux
      - git
      - openssh
      - htop
      - mupdf

- name: Install tools that don't require Ansible configuration (Chris specific)
  when: not minimal
  pacman:
    name:
      - lsof
      - reflector
      - maim
      - slop  # optdepends for `screenshot --select`
      - xclip
      - pass
      # For duply
      - rustup
      - mpv
      - pacman-contrib
      - ctags
      - bind-tools
      - powertop
      - clipmenu
      - zsh-syntax-highlighting
      - xdotool

- name: Install basic tools requiring aur (Chris specific)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes
  when: not minimal
  with_items:
    - nota
    - google-chrome
    - xlogin-git
  become: yes
  become_user: makepkg

- name: Install laptop tools
  aur: name={{ item }} skip_installed=yes
  with_items:
    - bats
  when: laptop|bool
  become: yes
  become_user: makepkg
