---
- name: Install fonts
  pacman: name=ttf-droid state=present

- name: Install fontconfig cache clear hook
  copy: src=files/fontconfig-clear-cache.hook dest=/usr/share/libalpm/hooks/fontconfig-clear-cache.hook

- name: 'Workaround for https://bugs.archlinux.org/task/63205'
  file: dest=/etc/fonts/conf.d/{{ item }}.conf src=/dev/null state=link
  with_items:
    - 60-droid-sans-mono
    - 65-droid-kufi
    - 65-droid-sans
    - 65-droid-serif

# Not sure why the pacman hook sometimes doesn't work, but for now...
- name: Always flush font cache
  command: fc-cache -rfv
  changed_when: false
