---
- name: Copy pacman configuration
  template: src=files/pacman.conf dest=/etc/pacman.conf

- name: Update package lists
  pacman: update_cache=yes
  changed_when: false

- name: Copy makepkg configuration
  copy: src=files/makepkg.conf dest=/etc/makepkg.conf
