---
- name: Remove tools that are no longer used
  pacman:
    state: absent
    extra_args: "--recursive"
    name:
      - okular
      - emojione-color-font
      - lib32-apulse
      - ltrace
      - skype
      - ndenv
      - node-build
      - pkgfile
      - openvpn-update-resolv-conf  # now managed by ansible directly
      - cython
      - youtube-dl  # done through pyenv
      - frogr
      - urlscan
      - xorg-xgamma
      - laptop-mode
      - docker
      - netatop-dkms
      - netatop
      - gvfs-mtp
      - mtpfs
      - mcelog  # not in community or aur any more
      - jfsutils
      - nano
      - pcmciautils
      - reiserfsprogs
      - s-nail
      - evince
      - acpi
      - vlock-original
      - screenkey
      - xprintidle
      - prompter
      - gnome-icon-theme
      - arch-install-scripts
      - autossh
      - pinta
      - lshw
      - gthumb
      - libreoffice-fresh
      - xautolock
      - xbanish
      - logrotate
      - wireshark-cli
      - nmap
      - tcpdump
      - nethogs
      - alsa-utils
      - notmuch
      - notmuch-mutt
      - isync
      - openvpn
      - ntp
      - firefox-unbranded-bin
      - firefox
      - chromium
      - certbot
      - thermald
      - pacaur
      - cower
      - bluejeans
      - pkgbuild-introspection
      - slock
      - tor-browser-en
      - kid3
      - dhclient
      - flashplugin
      - dmidecode
      - id3v2
      - antiword
      - tigervnc
      - cern-vdt
      - timeshift
      - aria2
      - mercurial
      - ngrep
      - mtr
      - netbrake
      - phonon-qt5
      - phonon-qt5-gstreamer
      - smartmontools
      - tk
      - xorg-xlsclients
      - xorg-xdpyinfo
      - xorg-xwininfo
      - gimp-plugin-gmic
      - gmic
      - pulseaudio-modules-bt-git
      - libldac
      - atop
      - texlive-bibtexextra
      - biber
      - bluez-tools
      - busybox
      - cmake
      - docx2txt
      - iftop
      - macchanger
      - moreutils
      - mupdf-tools
      - pdftk-bin
      - pv
      - wdiff
      - whois
      - wireless_tools
      - fcitx-gtk2
      - fcitx-qt5
      - zenity
      - wmname
      - python-sphinx
      - pandoc-bin
      - acpi_call
      - lvm2
      - mdadm
      - lenovo-throttling-fix-git
      - ifplugd
      - xfce4-notifyd
      - acestream-launcher

- name: Remove unused files
  file: path={{ item }} state=absent
  with_items:
    - /etc/udev/rules.d/70-laptop-net.rules
    - /etc/conf.d/wireless-regdom
    - /etc/udev/rules.d/99-deadline-for-ssd.rules
    - /etc/cron.d/clear-corrupt-journals
    - /etc/modprobe.d/99-i915.conf
    - /etc/systemd/system/localepurge.service
    - /etc/systemd/system/localepurge.timer
    - /usr/local/bin/powertargets
    - /usr/local/bin/powerdown
    - /usr/local/bin/powerup
    - /etc/systemd/system/powerdown.service
    - /etc/systemd/system/powerup.service
    - /etc/acpi/events/ansible
    - /etc/X11/xorg.conf.d/99-xorg-intel-tearing.conf
    - /etc/modules-load.d/no-wifi-power-save.conf
    - /etc/sysctl.d/99-laptop.conf
    - /etc/sysctl.d/99-dirty.conf
    - /etc/sysctl.d/99-sysrq.conf
    - /etc/sysctl.d/99-trace.conf
    - /usr/share/atop/atop.daily
    - /etc/systemd/system/slock.service
    - /etc/systemd/system/dev-mapper-swap.swap.d/override.conf
    - /etc/systemd/system/dev-mapper-swap.swap.d
    - /etc/modprobe.d/no-wifi-power-save.conf
    - /etc/tmpfiles.d/disable-pm-async.conf
    - /etc/default/tlp

- name: Remove old crons (now timers)
  file: path={{ item }} state=absent
  with_items:
    - /etc/cron.d/download-updates
    - /etc/cron.d/clean-cache
    - /etc/cron.d/fstrim
    - /etc/cron.d/i8kfan
    - /etc/cron.d/pkgfile
    - /etc/cron.d/purge-atop-logs
    - /etc/cron.d/reflector
