---
- name: Install mosh
  pacman: name=mosh state=present
  when: not minimal

- name: Install SSH daemon
  pacman: name=openssh state=present

- name: Create SSH group
  group: name=ssh state=present

- name: Configure SSH daemon
  copy: src=files/sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd

- name: Enable SSH daemon
  service: name=sshd state=started enabled=yes

- copy: src=files/rev.service dest=/etc/systemd/system/rev.service mode=644

- name: Enable rev service
  systemd: name=rev state=started enabled=yes daemon_reload=yes
