---
- name: Copy udev settings for T460s
  copy: src=files/udev/t460s.rules dest=/etc/udev/rules.d/99-machinespec.rules
  when: model in ["T460s", "T470s", "X1 Carbon"]

- name: Set I/O schedulers
  template: src=files/udev/io-schedulers.rules dest=/etc/udev/rules.d/99-io-schedulers.rules

- name: Set wifi powersave
  template: src=files/udev/wifi-powersave.rules dest=/etc/udev/rules.d/99-wifi-powersave.rules

- name: Set FUSE config
  copy: src=files/fuse.conf dest=/etc/fuse.conf

- copy: src=files/enable-thinkpad-fan-management dest=/etc/modprobe.d/enable-thinkpad-fan-management.conf
